### ISSUE TITLE
Small man page typo

### ISSUE THREAD

**Issue by jccleaver** [nathanweeks/ipcmd#2]
Not totally sure what the intended macro is here. Located at https://github.com/nathanweeks/ipcmd/blob/master/man/man1/ipcmd.1#L92

Fedora 30's rpmlint throws:
W: manual-page-warning /usr/share/man/man1/ipcmd.1.gz 92: warning: macro `"' not defined

**Comment by nathanweeks** [comment]
I suspect I had tried (and failed) to comment-out that line. Fixed (along with a couple other typos and a warning that `mandoc -T lint` threw) in 586c90005749d5698bd7c458fe1adbfc31003f71.

Thanks!
